### PR TITLE
✏ Add support for discord.js v14 

### LINKED ISSUE #169: TypeError: discord_js_1.Intents is not a constructor
**Promise:**
```
Promise {
  <rejected> TypeError: discord_js_1.Intents is not a constructor
      at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:47:19
      at step (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:33:23)
      at Object.next (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:14:53)
      at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:4:12)
      at module.exports (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:41:54)
      at Object.<anonymous> (/home/pi/Bots/Popcorn/Structures/index.js:17:1)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
}
```

**Reason:**
```
TypeError: discord_js_1.Intents is not a constructor
    at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:47:19
    at step (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:33:23)
    at Object.next (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:14:53)
    at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:4:12)
    at module.exports (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:41:54)
    at Object.<anonymous> (/home/pi/Bots/Popcorn/Structures/index.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
 ```

### PR DESCRIPTION
**Pull request by lolollllo**
Closes #169 & #171
Supersedes #170

### CODE REVIEW

**Comment by KingTeox** [comment]
I think it's kind of hard for him to accept the update, me I've already made a pull #170 doing the index.ts update and he hasn't done anything so far, dead project literally.

**Comment by KingTeox** [comment]
and it's easier for you to launch the package than waiting for the owner, There are a lot of people waiting for this.

**Comment by lolollllo** [comment]
Oh sure @KingTeox, ill publish `@lolollllo/discord-logs`

**Comment by lolollllo** [comment]
I'll keep this PR open though.

**Comment by zachjmurphy** [comment]
I have published a v14 version of this project here that not only is v14 supported but also implements the pull requests #167 #156 #151: https://github.com/zachjmurphy/discord-logs

You can find the NPM package here:
https://www.npmjs.com/package/@zachjmurphy/discord-logs

**Review by Androz2091 — APPROVED** [review]
Awesome thank you

**Pull request merged**
